# Building a Custom Classifier

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")
                    ],
                    columns=['text', 'sentiment'])

In [3]:
data.head(10)

                                                text sentiment
0    i love spending time with my friends and family  positive
1    that was the best meal i've ever had in my life  positive
2  i feel so grateful for everything i have in my...  positive
3  i received a promotion at work and i couldn't ...  positive
4  watching a beautiful sunset always fills me wi...  positive
5  my partner surprised me with a thoughtful gift...  positive
6  i am so proud of my daughter for graduating wi...  positive
7  listening to my favorite music always puts me ...  positive
8  i love the feeling of accomplishment after com...  positive
9           i am excited to go on vacation next week  positive

In [4]:
# Shuffle the data and reset the index
# frac = 1 means take 100% from the data
data = data.sample(frac=1).reset_index(drop=True)

Index   Category
0       Sport
1       Tech
2       Politics
3       Business

Index   Category
2       Politics
0       Sport
3       Business
1       Tech

In [5]:
data.head(10)

                                                text sentiment
0  i'm feeling sad because i miss my friends who ...  negative
1  my car broke down and it's going to be expensi...  negative
2  the traffic during my commute is always so fru...  negative
3  i received a promotion at work and i couldn't ...  positive
4  i'm frustrated because i can't seem to make pr...  negative
5    i love spending time with my friends and family  positive
6   i received a parking ticket and it ruined my day  negative
7  watching a beautiful sunset always fills me wi...  positive
8    that was the best meal i've ever had in my life  positive
9  i love the feeling of accomplishment after com...  positive

In [6]:
X = data['text']
y = data['sentiment']

In [7]:
# Text Vectorization using Bag of Words (BoW)
# CountVectorizer converts text into a matrix of word counts

countvec = CountVectorizer()

# Learn the vocabulary and transform the text into a document-term matrix
countvec_fit = countvec.fit_transform(X)

# Convert the matrix into a DataFrame
# Each row = a document
# Each column = a word
# Each value = the number of times the word appears in the document
bag_of_words = pd.DataFrame(
    countvec_fit.toarray(),
    columns=countvec.get_feature_names_out()
)

In [8]:
bag_of_words

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
8,0,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
9,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
16,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
17,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Dataset
#    ↓
#    ├── 70% → Training
#    │          X_train + y_train
#    │
#    └── 30% → Testing
#               X_test + y_test

# Set random_state for reproducible train-test splitabs

# split into train and test data
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size=0.3, random_state = 40)

# Logistic Regression

In [10]:
lr = LogisticRegression(random_state=1).fit(X_train, y_train)

In [11]:
y_pred_lr = lr.predict(X_test)

In [12]:
accuracy_score(y_pred_lr, y_test)

0.3333333333333333

In [13]:
y_pred_lr

array(['negative', 'negative', 'negative', 'negative', 'negative',
       'negative'], dtype=object)

In [14]:
y_test

9     positive
19    negative
13    positive
4     negative
8     positive
11    positive
Name: sentiment, dtype: object

In [15]:
print(classification_report(y_test, y_pred_lr, zero_division=0))

              precision    recall  f1-score   support

    negative       0.33      1.00      0.50         2
    positive       0.00      0.00      0.00         4

    accuracy                           0.33         6
   macro avg       0.17      0.50      0.25         6
weighted avg       0.11      0.33      0.17         6

Precision → How many predicted positives were actually positive?
Recall    → How many actual positives were correctly found?
F1-score  → Balance between precision and recall.
Support   → Number of samples in each class.
Accuracy  → How many predictions were correct overall?
Macro avg → Average of all classes equally.
Weighted avg → Average considering the number of samples per class.

# Naive Bayes

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
nb = MultinomialNB().fit(X_train, y_train)

In [18]:
y_pred_nb = nb.predict(X_test)

In [19]:
accuracy_score(y_pred_nb, y_test)

0.5

In [20]:
y_pred_nb

array(['positive', 'negative', 'negative', 'positive', 'negative',
       'positive'], dtype='<U8')

In [21]:
y_test

9     positive
19    negative
13    positive
4     negative
8     positive
11    positive
Name: sentiment, dtype: object

In [22]:
print(classification_report(y_test, y_pred_nb, zero_division=0))

              precision    recall  f1-score   support

    negative       0.33      0.50      0.40         2
    positive       0.67      0.50      0.57         4

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.56      0.50      0.51         6

# Linear Support Vector Machine

In [23]:
from sklearn.linear_model import LogisticRegression, SGDClassifier

In [24]:
svm = SGDClassifier().fit(X_train, y_train)
# possible hyper params, loss function, regularization

In [25]:
y_pred_svm = svm.predict(X_test)

In [26]:
accuracy_score(y_pred_svm, y_test)

0.3333333333333333

In [27]:
y_pred_svm

array(['negative', 'negative', 'negative', 'negative', 'negative',
       'negative'], dtype='<U8')

In [28]:
y_test

9     positive
19    negative
13    positive
4     negative
8     positive
11    positive
Name: sentiment, dtype: object

In [29]:
print(classification_report(y_test, y_pred_svm, zero_division=0))

              precision    recall  f1-score   support

    negative       0.33      1.00      0.50         2
    positive       0.00      0.00      0.00         4

    accuracy                           0.33         6
   macro avg       0.17      0.50      0.25         6
weighted avg       0.11      0.33      0.17         6