# Parts of Speech (POS) Tagging

## 📌 What is POS Tagging?

**Parts of Speech (POS) Tagging** is the process of assigning a grammatical category to each word in a sentence.

For example:

> **The quick brown fox jumps over the lazy dog.**

Each word has a different grammatical role.

---

## 🔹 Common POS Tags

| Tag   | Meaning                     | Example         |
| ----- | --------------------------- | --------------- |
| `NN`  | Noun                        | dog, book       |
| `NNS` | Plural Noun                 | dogs, books     |
| `NNP` | Proper Noun                 | John, Paris     |
| `VB`  | Verb                        | run, eat        |
| `VBD` | Past Tense Verb             | ran, ate        |
| `VBG` | Gerund / Present Participle | running, eating |
| `VBZ` | Verb, 3rd person singular   | jumps, runs     |
| `JJ`  | Adjective                   | beautiful, tall |
| `RB`  | Adverb                      | quickly, slowly |
| `PRP` | Pronoun                     | he, she, they   |
| `IN`  | Preposition                 | in, on, under   |
| `DT`  | Determiner                  | the, a, an      |

---

## 💡 Why is POS Tagging Important?

POS Tagging is useful in many **NLP applications**, such as:

* **Named Entity Recognition (NER)**
* **Text Classification**
* **Machine Translation**
* **Information Extraction**
* **Question Answering**
* **Sentiment Analysis**
* **Syntactic Parsing**

### Simple NLP Pipeline

```text
Raw Text
   ↓
Tokenization
   ↓
POS Tagging
   ↓
Further NLP Processing
   ↓
NLP Application
```

In [1]:
import spacy
import pandas as pd

In [2]:
# en → English 🇬🇧
# core → Core NLP tasks
# web → Model trained on web text
# sm → Small model
nlp = spacy.load('en_core_web_sm')

if you are running this for the first time, or recieve an error "Can't find model 'en_core_web_sm'", 
then please run the follwing in your terminal: python -m spacy download en_core_web_sm

In [3]:
# our text is from jane austin's 'emma'
# we have removed punctuation, lowercased but left in stop words
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [4]:
# create a spacy doc from our text - this will generate tokens and their assosciated pos tags
spacy_doc = nlp(emma_ja)

In [5]:
# extract the tokens and pos tags into a dataframe
pos_df = pd.DataFrame(columns=['token', 'pos_tag'])

In [6]:
pos_df

Empty DataFrame
Columns: [token, pos_tag]
Index: []

In [7]:
pos_df = pd.DataFrame([
    {'token': token.text, 'pos_tag': token.pos_}
    for token in spacy_doc
])

In [8]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [9]:
# token frequency count
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)
pos_df_counts.head(10)

    token pos_tag  counts
88     of     ADP      14
49    had     AUX       9
54    her    PRON       9
111   the     DET       8
6     and   CCONJ       8
0       a     DET       6
114    to    PART       5
61     in     ADP       4
13   been     AUX       4
120  very     ADV       4

In [10]:
# counts of pos_tags
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [11]:
# see most common nouns
nouns = pos_df_counts[pos_df_counts.pos_tag == "NOUN"][0:10]
nouns

         token pos_tag  counts
48   governess    NOUN       3
46      friend    NOUN       3
130      years    NOUN       2
35        emma    NOUN       2
28   daughters    NOUN       2
103    sisters    NOUN       2
82      mother    NOUN       2
89      office    NOUN       1
78    mistress    NOUN       1
75    mildness    NOUN       1

In [12]:
# see most common verbs
verbs = pos_df_counts[pos_df_counts.pos_tag == "ADJ"][0:10]
verbs

           token pos_tag  counts
70        little     ADJ       2
91           own     ADJ       1
86       nominal     ADJ       1
79          more     ADJ       1
102        short     ADJ       1
98          rich     ADJ       1
34         early     ADJ       1
26   comfortable     ADJ       1
25        clever     ADJ       1
16          best     ADJ       1

# Named Entity Recognition (NER)

**Named Entity Recognition (NER)** is an NLP technique used to identify and classify important entities in a text.

Instead of treating every word as just a word, NER determines **what a word or phrase represents**.

### Example

Consider the sentence:

> **"Ahmed works at Microsoft in Cairo."**

NER can identify:

| Text      | Entity       |
| --------- | ------------ |
| Ahmed     | PERSON       |
| Microsoft | ORGANIZATION |
| Cairo     | LOCATION     |

So:

* **Ahmed → PERSON** = a person
* **Microsoft → ORGANIZATION** = a company or organization
* **Cairo → LOCATION** = a place

---


## Common Named Entity Labels

| Label     | Meaning                | Example         |
| --------- | ---------------------- | --------------- |
| `PERSON`  | Person                 | Ahmed           |
| `ORG`     | Organization / Company | Microsoft       |
| `GPE`     | Geopolitical Entity    | Cairo           |
| `DATE`    | Date                   | August 30, 2026 |
| `TIME`    | Time                   | 10 AM           |
| `MONEY`   | Monetary value         | $500            |
| `PRODUCT` | Product                | iPhone          |
| `EVENT`   | Event                  | Olympics        |

## POS Tagging vs NER

### POS Tagging

POS Tagging identifies the **grammatical role** of a word.

For example:

```text
Ahmed → PROPN
works → VERB
at → ADP
```

### Named Entity Recognition

NER identifies **what an entity represents**.

```text
Ahmed → PERSON
Microsoft → ORG
Cairo → GPE
```

### Simple Difference

**POS Tagging → What type of word is it grammatically?**

**NER → What real-world entity does it represent?**

In [13]:
import spacy
from spacy import displacy
from spacy import tokenizer
import re
#nlp = spacy.load('en_core_web_sm')
from IPython.display import display

In [14]:
google_text = "Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet."
print(google_text)

Google was founded on September 4, 1998, by computer scientists Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of its stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.

In [15]:
spacy_doc = nlp(google_text)

In [16]:
for word in spacy_doc.ents:
    print(word.text,word.label_)

Google ORG
September 4, 1998 DATE
Larry Page PERSON
Sergey Brin PERSON
PhD WORK_OF_ART
Stanford University ORG
California GPE
about 14% PERCENT
56% PERCENT
IPO ORG
2004 DATE
2015 DATE
Google ORG
Alphabet Inc. ORG
Alphabet ORG
Alphabet ORG
Sundar Pichai PERSON
Google ORG
October 24, 2015 DATE
Larry Page PERSON
Alphabet GPE
December 3, 2019 DATE
Pichai PERSON
Alphabet GPE

In [17]:
# displacy → spaCy's visualization tool.
# render() → displays the document visually.
# spacy_doc → the spaCy Doc object containing your processed text.
# style="ent" → tells spaCy to display Named Entities.
# jupyter=True → tells spaCy that you are working inside Jupyter Notebook, so it renders the visualization as HTML.
displacy.render(spacy_doc,style="ent",jupyter=True)

In [18]:
google_text_clean = re.sub(r'[^\w\s]', '', google_text).lower() # remove punctuation and lowercase
print(google_text_clean)

google was founded on september 4 1998 by computer scientists larry page and sergey brin while they were phd students at stanford university in california together they own about 14 of its publicly listed shares and control 56 of its stockholder voting power through supervoting stock the company went public via an initial public offering ipo in 2004 in 2015 google was reorganized as a wholly owned subsidiary of alphabet inc google is alphabets largest subsidiary and is a holding company for alphabets internet properties and interests sundar pichai was appointed ceo of google on october 24 2015 replacing larry page who became the ceo of alphabet on december 3 2019 pichai also became the ceo of alphabet

In [19]:
spacy_doc_clean = nlp(google_text_clean)

In [20]:
for word in spacy_doc_clean.ents:
    print(word.text,word.label_)

google ORG
september 4 1998 DATE
stanford university ORG
california GPE
about 14 CARDINAL
56 CARDINAL
2004 DATE
2015 DATE
alphabet inc google ORG
google ORG
october 24 2015 DATE
larry PERSON
december 3 2019 DATE

In [21]:
displacy.render(spacy_doc_clean,style="ent",jupyter=True)